2018-11-09 14:27:19,196 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:28:26,732 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:36:10,660 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:38:32,463 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:38:46,521 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:52:55,881 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 14:58:48,168 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 15:08:45,334 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 15:09:47,938 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 15:59:36,219 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 22:04:14,765 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 22:04:20,249 ERROR: Exception on /explore [GET] [in /home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/austie/microblog/app/routes.py", line 124, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/austie/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/austie/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/austie/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/austie/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2018-11-09 22:04:49,129 ERROR: Exception on /explore [GET] [in /home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/austie/microblog/app/routes.py", line 124, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/austie/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/austie/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/austie/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/austie/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2018-11-09 22:12:58,947 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
2018-11-09 22:13:03,912 ERROR: Exception on /explore [GET] [in /home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/austie/microblog/app/routes.py", line 124, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/austie/microblog/py3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/austie/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/austie/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/austie/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/home/austie/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2018-11-09 22:20:42,344 INFO: Microblog startup [in /home/austie/microblog/app/__init__.py:42]
